"""add subcategory unique constraint

Revision ID: 570075bc1669
Revises: 124bdceb4a4d
Create Date: 2026-01-07 17:39:46.909011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '570075bc1669'
down_revision: Union[str, Sequence[str], None] = '124bdceb4a4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category_id', sa.Integer(), nullable=False))
    op.alter_column('products', 'current_stock',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'])
    op.create_unique_constraint('uq_subcategory_name_category', 'subcategories', ['name', 'category_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_subcategory_name_category', 'subcategories', type_='unique')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.alter_column('products', 'current_stock',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('products', 'category_id')
    # ### end Alembic commands ###
