"""add alerts table

Revision ID: 7c33527783a0
Revises: 4a0fcf95da38
Create Date: 2026-01-29 20:32:41.768155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7c33527783a0'
down_revision: Union[str, Sequence[str], None] = '4a0fcf95da38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('alert_type', sa.String(length=50), nullable=False))
    op.add_column('alerts', sa.Column('status', sa.String(length=20), nullable=True))
    op.drop_column('alerts', 'active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('alerts', 'status')
    op.drop_column('alerts', 'alert_type')
    # ### end Alembic commands ###
